### PR TITLE
Style and documentation

### PR DESCRIPTION
**Pull request by JonHenin**
Update master with updated documentation and PEP8 style guidelines

### CODE REVIEW

**Comment by moaldanabernal** [comment]
In process_csv.py module, could you give more sense to this variable 'w',
        w = csv.DictWriter(csvfile, fieldnames=fieldnames)
        w.writeheader()
        w.writerows(records)

Could you write a little comment about 'transform_record',
       records.append(msds510.transform_record(dictionary))

**Comment by JonHenin** [comment]
Thanks, added additional comments for clarity.

**Comment by moaldanabernal** [comment]
I checked the main files from the past assignment, make_report.py, process_csv.py, and util.py
I can see the best practices in your code.

Just a few more details,
	   
I think, you are not using these functions, which are coded in util.py
days_since_joined
get_date_joined

I can see several modules, such as convert_to_utf8.py, read.csv.py, read_csv_dict.py, test_util_module.py, and write_csv.py
Perhaps your whole project would be a little fragmented, could you include these modules in util.py?

**Comment by JonHenin** [comment]
Thanks @moaldanabernal, those missing functions are in the test_util_module.py and as you eluded to convert_to_utf8.py, read_csv.py, read_csv_dict.py, test_util_module.py and write_csv.py are all from the prior assignment rather than the midterm.  Unfortunately they are in the same folder structure and I didn't want to touch those files until my stuff was graded as I just gave a link.  If this was real though I would agree that it is fragmented and I wouldn't have them, but for the assignment sake it said to make those files and have them be runnable as stand alone scripts.

**Comment by Lemonchasers** [comment]
It all looks as if it is best practice and I can see that you have comments as to what everything is doing. Overall, I think it looks very good.

**Comment by krytaylor** [comment]
You project is easy to read, and very organized. I think that you did well completed the overall project.

**Pull request merged**
